substitutions:
  area: mtr.bsm
  device_name: circulation-pump
  friendly_name: Circulation Pump
  relay_restore_mode: "RESTORE_DEFAULT_OFF" # or ALWAYS_OFF, ALWAYS_ON
  direct_mode: "0" # -1 to disable, else toggle amount
  double_toggle: "false"
  toggle_duration: "250" # Time in ms
packages:
  api:
    file: packages/components/api.yaml
  logger:
    file: packages/components/logger.yaml
  ota:
    file: packages/components/ota.yaml
  restart:
    file: packages/components/restart.yaml
  secrets:
    file: packages/components/secrets.yaml
  time:
    file: packages/components/time.yaml
  version:
    file: packages/components/version.yaml
  wifi:
    file: packages/components/wifi.yaml
  board:
    file: packages/boards/esp8285.yaml
  device_base:
    file: packages/devices/sonoff-mini.yaml
