substitutions:
  area: ofc.brn
  device_name: circulation-pump
  friendly_name: Circulation Pump
  relay_restore_mode: "RESTORE_DEFAULT_OFF" # or ALWAYS_OFF, ALWAYS_ON
  direct_mode: "0" # -1 to disable, else toggle amount
  double_toggle: "false"
  toggle_duration: "250" # Time in ms
packages:
  - !include packages/devices/sonoff-mini.yaml
