substitutions:
  area: mtr.bsm
  device_name: heat-pump
  friendly_name: Heat Pump

packages:
  device: !include devices/atom-lite.yaml

uart:
  id: mod_bus
  tx_pin: 26
  rx_pin: 32
  baud_rate: 9600
  stop_bits: 1
  data_bits: 8

modbus:
  id: modbus_versati3
  uart_id: mod_bus

modbus_controller:
  - id: versati3
    address: 0x01
    modbus_id: modbus_versati3
    setup_priority: -10
    update_interval: 30s

number:
  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_t_water_tank
    name: "Hot Water Tank Temperature"
    device_class: "temperature"
    address: 13
    register_type: holding
    value_type: U_WORD
    min_value: 40
    max_value: 80
    unit_of_measurement: '°C'

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_delta_hot_water
    name: "Hot Water Delta Temperature"
    device_class: "temperature"
    address: 31
    register_type: holding
    value_type: U_WORD
    min_value: 2
    max_value: 8
    step: 1
    unit_of_measurement: '°C'

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_wot_heat
    name: "Water Outlet Temperature - Heat"
    device_class: "temperature"
    address: 10
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: '°C'

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_rt_heat
    name: "Room Temperature - Heat"
    device_class: "temperature"
    address: 12
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: '°C'

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_upper_wt_heat
    name: "Upper Water Temperature - Heat"
    device_class: "temperature"
    address: 21
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: '°C'

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_lower_wt_heat
    name: "Lower Water Temperature - Heat"
    device_class: "temperature"
    address: 22
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: '°C'

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_upper_at_heat
    name: "Upper Ambient Temperature - Heat"
    device_class: "temperature"
    address: 17
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: '°C'

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_lower_at_heat
    name: "Lower Ambient Temperature - Heat"
    device_class: "temperature"
    address: 18
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: '°C'

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_upper_rt_heat
    name: "Upper Room Temperature - Heat"
    device_class: "temperature"
    address: 19
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: '°C'

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_lower_rt_heat
    name: "Lower Room Temperature - Heat"
    device_class: "temperature"
    address: 20
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: '°C'

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_power_limit
    name: "Power Limit"
    device_class: "power"
    address: 43
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: 'kW'

select:
  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_tank_heater
    name: "Tank Heater"
    address: 36
    value_type: U_WORD
    optionsmap:
      "Setting 1": 1
      "Setting 2": 2
  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_mode
    name: "gree_mode"
    address: 2
    value_type: U_WORD
    optionsmap:
      "Heat": 1
      "Hot Water": 2
      "Cool + Hot Water": 3
      "Heat + Hot Water": 4
      "Cool": 5
  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_thermostat
    name: "Thermostat"
    address: 39
    value_type: U_WORD
    optionsmap:
      "Without": 0
      "Air": 1
      "Air + Hot Water": 2

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_status_thermostat
    name: "Thermostat Status"
    address: 132
    value_type: U_WORD
    optionsmap:
      "Cool": 1
      "Heat": 2
      "Off": 3

switch:
  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_on_off
    name: "Power"
    address: 42
    register_type: holding
    value_type: U_WORD
    command_on: 0xAA
    command_off: 0x55
    icon: "mdi:power"
    device_class: "switch"

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_coil_water_tank
    name: "Water Tank"
    register_type: coil
    address: 29
    bitmask: 1
    device_class: "outlet"

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_coil_ctrl_state
    name: "Control State"
    register_type: coil
    address: 17
    bitmask: 1
    device_class: "switch"
  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_coil_quiet_ctrl
    name: "Quiet Mode"
    register_type: coil
    address: 21
    bitmask: 1
    device_class: "switch"

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_coil_wdwdepend
    name: "Weather Dependent Mode"
    register_type: coil
    address: 22
    bitmask: 1
    device_class: "switch"

binary_sensor:

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_coil_tank_heater_state
    name: "Water Tank Heater State"
    device_class: "heat"
    address: 173
    register_type: coil
    entity_category: "diagnostic"

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_coil_tank_temp_sensor_error
    name: "Water Tank Temperature Sensor Error"
    device_class: "problem"
    address: 156
    register_type: coil
    entity_category: "diagnostic"
  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_coil_compressor_state
    name: "Compressor State"
    address: 80
    register_type: coil
    device_class: "power"
    entity_category: "diagnostic"
  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_coil_crankcase_heater_state
    name: "Crankcase Heater State"
    address: 84
    register_type: coil
    device_class: "heat"
    entity_category: "diagnostic"

sensor:
  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_status_t_tank
    name: "Hot Water Tank Temperature"
    device_class: "temperature"
    state_class: "measurement"
    address: 128
    register_type: holding
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: '°C'
  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_delta_heat
    name: "Delta Temperature - Heat"
    device_class: "temperature"
    state_class: "measurement"
    address: 30
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: '°C'

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_delta_room_temp
    name: "Delta Room Temperature"
    device_class: "temperature"
    state_class: "measurement"
    address: 32
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: '°C'

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_current_limit
    name: "Current Limit"
    device_class: "current"
    state_class: "measurement"
    address: 38
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: 'A'

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_status_unit_status
    name: "Unit Status"
    state_class: "measurement"
    address: 117
    register_type: holding
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_status_t_outdoor
    name: "Outdoor Temperature"
    device_class: "temperature"
    state_class: "measurement"
    address: 118
    register_type: holding
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

    unit_of_measurement: '°C'

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_status_t_water_out
    name: "Water Outlet Temperature"
    device_class: "temperature"
    state_class: "measurement"
    address: 125
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: '°C'

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_status_t_water_in
    name: "Water Inlet Temperature"
    device_class: "temperature"
    state_class: "measurement"
    address: 127
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: '°C'

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: t_remote_room
    name: "Remote Room Temperature"
    device_class: "temperature"
    state_class: "measurement"
    address: 129
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: '°C'

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_status_t_weather_depend
    name: "Weather Dependent Temperature"
    device_class: "temperature"
    state_class: "measurement"
    address: 137
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: '°C'

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_status_setting_frequency
    name: "Setting Frequency"
    state_class: "measurement"
    address: 142
    register_type: holding
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_status_running_frequency
    name: "Running Frequency"
    state_class: "measurement"
    address: 143
    register_type: holding
    value_type: U_WORD
