substitutions:
  area: gn.cs
  device_name: pond-power-plug
  friendly_name: Pond Power Plug
  current_res: "0.00257"
  voltage_div: "947"
packages:
  - !include packages/devices/cloudfree-smart-plug.yaml
