substitutions:
  current_res: "0.00290"
  voltage_div: "940"
  cf1_pin: GPIO14
packages:
  - !include ../components/api.yaml
  - !include ../components/logger.yaml
  - !include ../components/ota.yaml
  - !include ../components/restart.yaml
  - !include ../components/secrets.yaml
  - !include ../components/time.yaml
  - !include ../components/version.yaml
  - !include ../components/wifi.yaml
  - !include ../boards/esp8285.yaml
esphome:
  on_boot:
    then:
      - switch.turn_on: relay
      - output.turn_on: led
binary_sensor:
  - platform: gpio
    name: "${friendly_name} button"
    id: "relay_button"
    pin:
      number: GPIO13
      inverted: true
    on_press:
      then:
        - switch.toggle: relay
output:
  - platform: gpio
    pin: GPIO0
    inverted: true
    id: led
switch:
  - platform: gpio
    pin: GPIO15
    restore_mode: RESTORE_DEFAULT_OFF
    id: relay
    name: "${friendly_name} Relay"
    on_turn_on:
      - output.turn_on: led
    on_turn_off:
      - output.turn_off: led
status_led:
  pin:
    number: GPIO2
    inverted: true
sensor:
  - platform: hlw8012
    energy:
      name: "${friendly_name} Energy"
      unit_of_measurement: "Wh"
      icon: mdi:flash-outline
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO5
    cf1_pin: ${cf1_pin}
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    current:
      name: "${friendly_name} Current"
      unit_of_measurement: "A"
      accuracy_decimals: 3
      icon: mdi:flash-outline
    voltage:
      name: "${friendly_name} Voltage"
      unit_of_measurement: "V"
      icon: mdi:flash-outline
    power:
      name: "${friendly_name} Power"
      unit_of_measurement: "W"
      id: power
      icon: mdi:flash-outline
      on_value_range:
        - above: ${max_power}
          then:
            - output.turn_off: led
            - switch.turn_off: relay
    change_mode_every: 4
    update_interval: 10s
