substitutions:
  current_res: "${current_res}"
  voltage_div: "${voltage_div}"
packages:
  - !include ../components/api.yaml
  - !include ../components/logger.yaml
  - !include ../components/ota.yaml
  - !include ../components/restart.yaml
  - !include ../components/secrets.yaml
  - !include ../components/time.yaml
  - !include ../components/version.yaml
  - !include ../components/wifi.yaml
  - !include ../boards/esp01_1m.yaml
sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO05
    cf1_pin: GPIO14
    change_mode_every: 8
    update_interval: 10s
    current:
      name: ${friendly_name} Amperage
      icon: mdi:current-ac
      unit_of_measurement: A
    voltage:
      name: ${friendly_name} Voltage
      icon: mdi:flash-circle
      unit_of_measurement: V
    power:
      id: wattage
      name: ${friendly_name} Wattage
      icon: mdi:flash-outline
      unit_of_measurement: W
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
  - platform: total_daily_energy
    name: ${friendly_name} Total Daily Energy
    icon: mdi:circle-slice-3
    power_id: wattage
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
binary_sensor:
  - platform: gpio
    device_class: power
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: true
    name: ${friendly_name} Button
    on_press:
      - switch.toggle: relay
switch:
  - platform: gpio
    name: ${friendly_name}
    pin: GPIO15
    id: relay
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - script.execute: led_power_on
    on_turn_off:
      - script.execute: led_relay_off
output:
  - platform: esp8266_pwm
    id: output_blue_led
    pin:
      number: GPIO02
      inverted: true
light:
  - platform: monochromatic
    name: ${friendly_name} Light
    output: output_blue_led
    id: light_blue_led
interval:
  - interval: 2000ms
    then:
      - if:
          condition:
            for:
              time: 30s
              condition:
                not:
                  wifi.connected:
          then:
            - light.turn_on:
                id: light_blue_led
                brightness: 100%
script:
  - id: led_relay_off
    then:
      - light.turn_off:
          id: light_blue_led
  - id: led_power_on
    then:
      - light.turn_on:
          id: light_blue_led
          brightness: 80%
