packages:
  - !include ../components/api.yaml
  - !include ../components/logger.yaml
  - !include ../components/ota.yaml
  - !include ../components/restart.yaml
  - !include ../components/time.yaml
  - !include ../components/version.yaml
  - !include ../components/wifi.yaml
  - !include ../boards/esp01_1m.yaml
binary_sensor:
  - platform: gpio
    name: "${relay_1} Button"
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: "relay_1"
  - platform: gpio
    name: "${relay_2} Button"
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: "relay_2"
  - platform: gpio
    name: "${relay_3} Button"
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: "relay_3"
  - platform: gpio
    name: "${relay_4} Button"
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: "relay_4"
  - platform: status
    name: "Sonoff 4CH Pro Status"
switch:
  - platform: gpio
    name: "${relay_1}"
    pin: GPIO12
    id: "relay_1"
  - platform: gpio
    name: "${relay_2}"
    pin: GPIO5
    id: "relay_2"
  - platform: gpio
    name: "${relay_3}"
    pin: GPIO4
    id: "relay_3"
  - platform: gpio
    name: "${relay_4}"
    pin: GPIO15
    id: "relay_4"
