packages:
  api:
    file: ../components/api.yaml
  logger:
    file: ../components/logger.yaml
  ota:
    file: ../components/ota.yaml
  restart:
    file: ../components/restart.yaml
  secrets:
    file: ../components/secrets.yaml
  time:
    file: ../components/time.yaml
  version:
    file: ../components/version.yaml
  wifi:
    file: ../components/wifi.yaml
  board:
    file: ../boards/esp8285.yaml
sensor:
  - platform: wifi_signal
    name: ${device_name} Wifi Signal Strength
    update_interval: 60s
  - platform: uptime
    name: ${device_name} Uptime
binary_sensor:
  - platform: gpio
    pin: GPIO00
    id: reset
    internal: true
    filters:
      - invert:
      - delayed_off: 10ms
    on_press:
      - switch.toggle:
          id: relay_1
  - platform: gpio
    name: ${device_name}_status
    pin: GPIO04
    id: switch_1
    on_press:
      then:
        - switch.toggle:
            id: relay_1
    on_release:
      then:
        - switch.toggle:
            id: relay_1
switch:
  - platform: gpio
    name: ${device_name}_switch
    icon: "mdi:lightbulb_outline"
    pin: GPIO12
    id: relay_1
    restore_mode: restore_default_off
status_led:
  pin:
    number: GPIO13
    allow_other_uses: true
    inverted: true
output:
  - platform: esp8266_pwm
    id: blue_led
    pin:
      number: GPIO13
      allow_other_uses: true
    inverted: True
light:
  - platform: monochromatic
    name: ${device_name}_blueled
    output: blue_led
    internal: true # hides the Blue LED from HomeAssistant
