# https://esphome.io/packages/wifi.html
substitutions:
  domain: !secret domain
wifi:
  id: component_wifi
  ssid: !secret wifi_ssid
  use_address: "${device_name}.${area}.${zone}.${domain}"
  password: !secret wifi_password
  reboot_timeout: 10min
  ap:
    ssid: "${friendly_name} AP"
    password: !secret wifi_fallback_ssid_password
captive_portal:
sensor:
  - platform: wifi_signal
    id: sensor_wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 300s
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
    ssid:
      name: "${friendly_name} Connected SSID"
    bssid:
      name: "${friendly_name} Connected BSSID"
    mac_address:
      name: "${friendly_name} Connected MAC"
